environment.variables:
  datasource:
    url: jdbc:mysql://localhost:3306/3xpensetrckr?serverTimezone=UTC
    username: root
    password: password1

  mail:
    host: smtp.gmail.com
    port: 587
    username: valentin0519@gmail.com
    password: zjhs ejia yfyl ythx

